stages:
  - test
  - quality
  - docker

# Pipeline allowed but jobs manual
workflow:
  rules:
    - when: always

# ------------------------------------------------
# GLOBAL VARIABLES
# ------------------------------------------------
variables:
  PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

# ------------------------------------------------
# PLAYWRIGHT TESTS
# ------------------------------------------------
playwright_tests:
  stage: test
  when: manual
  image: mcr.microsoft.com/playwright/python:v1.58.0-jammy

  before_script:
    - pip install -r requirements.txt
    - playwright install --with-deps

  script:
    - pytest tests --alluredir=allure-results

  artifacts:
    when: always
    paths:
      - allure-results
      - reports

# ------------------------------------------------
# SONARCLOUD
# ------------------------------------------------
sonarqube_check:
  stage: quality
  when: manual
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]

  script:
    - sonar-scanner
        -Dsonar.projectKey=vijayhmsv93-group_vijayhmsv93-project
        -Dsonar.organization=vijayhmsv93-group
        -Dsonar.sources=.
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.login=$SONAR_TOKEN

# ------------------------------------------------
# DOCKER BUILD
# ------------------------------------------------
docker_build:
  stage: docker
  when: manual
  image: docker:latest
  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker build -t playwright-python-project .

  only:
    - main