stages:
  - test
  - quality
  - docker

# ------------------------------------------------
# RUN PIPELINE ONLY WHEN CLICKED
# ------------------------------------------------
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

# ------------------------------------------------
# GLOBAL VARIABLES
# ------------------------------------------------
variables:
  PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

# ------------------------------------------------
# PLAYWRIGHT TESTS + ALLURE
# ------------------------------------------------
playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.58.0-jammy

  before_script:
    - pip install -r requirements.txt
    - playwright install --with-deps

  script:
    - pytest tests --alluredir=allure-results

  artifacts:
    when: always
    paths:
      - allure-results
      - reports
    expire_in: 1 week

# ------------------------------------------------
# SONARCLOUD ANALYSIS
# ------------------------------------------------
sonarqube_check:
  stage: quality
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]

  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"

  cache:
    key: sonar
    paths:
      - .sonar/cache

  script:
    - sonar-scanner
        -Dsonar.projectKey=vijayhmsv93-group_vijayhmsv93-project
        -Dsonar.organization=vijayhmsv93-group
        -Dsonar.sources=.
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.login=$SONAR_TOKEN

# ------------------------------------------------
# DOCKER BUILD
# ------------------------------------------------
docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info

  script:
    - docker build -t playwright-python-project .

  only:
    - main