sonar.projectKey=vijayhmsv93-group_vijayhmsv93-project
sonar.organization=vijayhmsv93-group

sonar.projectName=vijayhmsv93-project

# ✅ Scan only source folders
sonar.sources=tests,utils,pages

# Python config
sonar.python.version=3.11

# ✅ Ignore non-python content
sonar.exclusions=\
**/*.c,\
**/*.cpp,\
**/*.h,\
**/*.hpp,\
**/node_modules/**,\
**/.venv/**,\
venv/**,\
allure-results/**,\
reports/**,\
.playwright/**,\
**/__pycache__/**

sonar.sourceEncoding=UTF-8